zc/Areas/Backend/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using zc.Filters;

namespace zc.Areas.Backend.Controllers
{
    public class HomeController : Controller
    {
        // GET: Backend/Home
        // [OperatorAuthorize]
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Default()
        {
            return View();
        }
    }
}

zc/Areas/Backend/Controllers/LogoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using zc.Commons;

namespace zc.Areas.Backend.Controllers
{
    public class LogoutController : Controller
    {
        // GET: Backend/Logout
        public ActionResult Index()
        {
            Session[SessionConstants.CURRENTOPERATOR] = null;
            return RedirectToAction("Index", "Login");
        }
    }
}

zc/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace zc.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

zc/Areas/Backend/Views/Home/Default.cshtml
@{
    ViewBag.Title = "Default";
}

<h2>欢迎</h2>

zc/Areas/Backend/Views/Home/Index.cshtml
@using zc.Commons
@using zc.Models
@{
    ViewBag.Title = "框架页";
}

<!--顶部-->
<div data-options="region:'north',border:false" class="div-top">
    <div class="page-top">
        <div style="float: left;padding-left: 20px;font-size:18px !important;">国源汇众筹会员管理后台</div>
        <div style="float: right; padding-right: 20px;">
            <span>操作员：@((Session[zc.Commons.SessionConstants.CURRENTOPERATOR] as _operator).oper_name)，您好！</span>
            <a href="@Url.Action("Index", "ModifyPwd")" onclick="javascript: $('#dlg').dialog('open'); return false;" style="color: white; text-decoration: underline;">修改密码</a>
            <span>&nbsp;&nbsp;&nbsp;&nbsp;</span>
            <a href="@Url.Action("Index", "Logout")" style="color: white; text-decoration: underline;">退出</a>
        </div>
    </div>
</div>

<!--左侧菜单-->
<div data-options="region:'center',border:false">
    <div class="easyui-layout" data-options="fit:true">
        <div data-options="region:'west',split:true,title:' '" class="div-left">
            <ul class="meau-nav" id="meau-nav">
                @{
                    var oper = Session[SessionConstants.CURRENTOPERATOR] as _operator;
                    var menus = (from role in oper.sysroles
                                 from menu in role.menus
                                 select menu).Distinct();
                    foreach (var menu in menus)
                    {
                        if(menu.menu_parent_id == 0)
                        {
                            <li>
                                <div class="link down">
                                    @menu.menu_name
                                </div>
                                <ul class="submenu">
                                    @foreach (var item in menus)
                                    {
                                        if (item.menu_parent_id == menu.menu_id)
                                        {
                                            <li class="m_t_3_1"><a href="javascript:;" src="@item.menu_url">@item.menu_name</a></li>
                                        }
                                    }
                                </ul>
                            </li>
                        }
                    }
                }
            </ul>
        </div>
        <div data-options="region:'center'">
            <div class="easyui-tabs" data-options="fit:true,border:false" id="tabs">
                <div title="首页" style="padding: 10px">

                    <iframe scrolling="auto" frameborder="0" src="@Url.Action("Default", "Home")" style="width:100%;height:98%;"></iframe>
                </div>
            </div>
        </div>
    </div>
</div>

<!--底部-->
<div class="div-bottom" data-options="region:'south',border:false">
    <div class="page-bottom">版权所有：四川国源汇科技</div>
</div>

<!--修改密码弹框-->
<div id="dlg" class="easyui-dialog" title="修改密码" style="width:400px;height:260px;padding:15px"
     data-options="modal:true,closed:true,buttons:'#dlg-buttons'">
    <style>
        #fmModifyPwd .text {
            padding: 5px 7px;
            width: 220px;
        }

        #fmModifyPwd label {
            display: inline-block;
            width: 6em;
            text-align: right;
        }
    </style>
    <form id="fmModifyPwd" action="@Url.Action("Index", "ModifyPwd")" method="post">
        <p>
            <label>原密码</label>
            <input type="password" name="oldPwd" class="text" />
        </p>
        <p>
            <label>新密码</label>
            <input type="password" name="newPwd" class="text" />
        </p>
        <p>
            <label>确认新密码</label>
            <input type="password" name="newPwdRepeat" class="text" />
        </p>
    </form>
</div>
<div id="dlg-buttons">
    <a href="javascript:;" class="easyui-linkbutton" iconCls="icon-ok" id="btnConfim" onclick="modifyPwd()">保存新密码</a>
    <a href="javascript:;" class="easyui-linkbutton" iconCls="icon-cancel" onclick="javascript:$('#dlg').dialog('close')">取消</a>
</div>
<script>
    function modifyPwd() {
        $('#fmModifyPwd').form('submit', {
            success: function (data) {
                data = eval("(" + data + ")");
                if (data.code != 200) {
                    $.messager.alert('系统消息', data.message, 'info');
                } else {
                    $('#dlg').dialog('close');
                    $('#fmModifyPwd').form('clear');
                }
            }
        });
    }
</script>

<script type="text/javascript">
    var theMainFrameCount = 0;

    function addTab(title, url) {
        var exists = document.getElementById("theMain_Frame" + (theMainFrameCount)) != null;
        if (exists) {
            var tabs = $('#tabs').tabs('tabs');
            $('#tabs').tabs('select', tabs.length - 1);
            var currTab = tabs[tabs.length - 1];
            if (url != undefined && currTab.panel('options').title != '首页') {
                $('#tabs').tabs('update',
                    {
                        tab: currTab,
                        options: {
                            title: title,
                            content: createFrame(url),
                            closable: true
                        }
                    });
            }
        } else {
            var content = createFrame(url);
            $('#tabs').tabs('add',
                {
                    title: title,
                    content: content,
                    closable: true
                });
        }
    }
    //创建iframe
    function createFrame(url) {
        var s = '<iframe id="theMain_Frame' + theMainFrameCount + '" scrolling="auto" frameborder="0" style="width:100%;height:98%;"></iframe>';
        s += '<script type="text/java' + 'script">$("#theMain_Frame' + theMainFrameCount + '").attr("src","' + url + '");</s' + 'cript>';
        return s;
    }

    $(function () {
        //菜单折叠
        $("#meau-nav .link").click(function () {
            if (this.className == "link down") {
                $(this).addClass("up").next("ul.submenu").slideToggle(300).siblings("ul.submenu").slideUp("slow");
            } else {
                $(this).removeClass("up").next("ul.submenu").slideToggle(300).siblings("ul.submenu").slideUp("slow");
            }
        });
        //点击子菜单样式变更
        $(".submenu li").click(function () {
            if (this.className == "m_t_3_1") {
                $(".submenu li").removeClass("m_t_3_2").addClass("m_t_3_1");
                $(this).removeClass("m_t_3_1").addClass("m_t_3_2");
                $(this).children("a").addClass("aHover");
            }
        });
        $(".submenu li a").click(function () {
            var $this = $(this);
            var href = $this.attr('src');
            var title = $this.find("div").length > 0 ? $this.find("div").text() : $this.text();
            addTab(title, href);
        });
    });
</script>