zc/Models/user.cs
namespace zc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("user")]
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            account_record = new HashSet<account_record>();
            bonus_record = new HashSet<bonus_record>();
            bonus_record1 = new HashSet<bonus_record>();
            cash_record = new HashSet<cash_record>();
        }

        [Key]
        public int user_id { get; set; }

        [Required]
        [StringLength(10)]
        public string user_code { get; set; }

        [Required]
        [StringLength(50)]
        public string user_name { get; set; }

        [Required]
        [StringLength(20)]
        public string user_phone { get; set; }

        [Required]
        [StringLength(20)]
        public string id_number { get; set; }

        [Required]
        [StringLength(50)]
        public string login_password { get; set; }

        [Required]
        [StringLength(50)]
        public string second_password { get; set; }

        public int referrer_id { get; set; }

        public int level_id { get; set; }

        [StringLength(50)]
        public string province { get; set; }

        [StringLength(50)]
        public string city { get; set; }

        [StringLength(50)]
        public string area { get; set; }

        [StringLength(200)]
        public string address { get; set; }

        [StringLength(50)]
        public string bank_name { get; set; }

        [StringLength(50)]
        public string account_num { get; set; }

        [StringLength(50)]
        public string wallet_adder { get; set; }

        public int user_status { get; set; }

        public int reg_money { get; set; }

        public DateTime register_time { get; set; }

        public DateTime? activate_time { get; set; }

        public int? activate_id { get; set; }

        [StringLength(1000)]
        public string user_remark { get; set; }

        [StringLength(1000)]
        public string user_remark1 { get; set; }

        [StringLength(1000)]
        public string user_remark2 { get; set; }

        [StringLength(1000)]
        public string user_remark3 { get; set; }

        public int? activate_type { get; set; }

        public bool? is_activate { get; set; }

        public string ref_url { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<account_record> account_record { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bonus_record> bonus_record { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bonus_record> bonus_record1 { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cash_record> cash_record { get; set; }

        public virtual level level { get; set; }

        public virtual user_account user_account { get; set; }

        [ForeignKey("referrer_id")]
        public virtual user referrer { get; set; }
    }
}

zc/Areas/Backend/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using zc.Commons;
using zc.Managers;

namespace zc.Areas.Backend.Controllers
{
    public class LoginController : Controller
    {

        private OperatorManager _operationManager = new OperatorManager();

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        // GET: Backend/Login
        [HttpPost]
        public ActionResult Index(string loginName, string loginPwd)
        {
            var success = _operationManager.Login(loginName, loginPwd);
            if (success)
            {
                //FormsAuthentication.SetAuthCookie(loginName, true);
                var currentOper = _operationManager.GetWithPermissions(loginName);
                Session[SessionConstants.CURRENTOPERATOR] = currentOper;
                return RedirectToAction("Index", "Home");
            }
            return View();
        }
    }
}

zc/Areas/Backend/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using zc.Commons;
using zc.Managers;
using zc.Models;
using zc.Models.ViewModels;
using zc.Filters;
namespace zc.Areas.Backend.Controllers
{
    //[OperatorAuthorize]
    public class UserController : Controller
    {
        private UserManager _userManager = new UserManager();

        public ActionResult Index()
        {
            return View();
        }

        #region 会员列表相关

        public ActionResult SearchNotActivatedUsers(string userName = "", string userPhone = "", int page = 1, int rows = 10)
        {
            if (Request.IsAjaxRequest())
            {
                var notActivatedUsers = _userManager.SearchNotActivedUsers(userName, userPhone, page, rows);
                var data = notActivatedUsers.Select(this.ToUserViewModel);
                var total = _userManager.SearchTotalOfNotActivatedUsers(userName, userPhone);
                return Json(new { total = total, rows = data });
            }
            //查询等级列表
            var level = this._userManager.GetLevelList();
            ViewBag.Levels = new SelectList(level, "level_money", "level_money");
            return View();
        }


        public ActionResult All(string userName, string userPhone, string idNumber, int? levelId, string province, string city, string area, string referrerUserName, int? userStatus, DateTime? beginRegDate, DateTime? endRegDate, DateTime? beginActiveDate, DateTime? endActiveDate, int page = 1, int rows = 10)
        {
            if (Request.IsAjaxRequest())
            {
                var users = this._userManager.GetAllUsers(userName, userPhone, idNumber, levelId, province, city, area, referrerUserName, userStatus, beginRegDate, endRegDate, beginActiveDate, endActiveDate, page, rows);
                var data = users.Select(u => new
                {
                    user_id = u.user_id,
                    user_code = u.user_code,
                    user_name = u.user_name,
                    user_phone = u.user_phone,
                    id_number = u.id_number,
                    level_name = u.level == null ? "" : u.level.level_name,
                    province = u.province,
                    city = u.city,
                    area = u.area,
                    address = u.address,
                    reg_money = u.reg_money,
                    referrer_name = u.referrer == null ? "无" : u.referrer.user_name,
                    user_status = UserStatusHelper.ToString(u.user_status),
                    register_time = u.register_time.ToString("yyyy-MM-dd HH:mm:ss"),
                    activate_time = u.activate_time == null ? "" : u.activate_time.Value.ToString("yyyy-MM-dd HH:mm:ss")
                });
                var total = this._userManager.GetAllUsersTotal(userName, userPhone, idNumber, levelId, province, city, area, referrerUserName, userStatus, beginRegDate, endRegDate, beginActiveDate, endActiveDate);
                return Json(new { total = total, rows = data });
            }
            return View();
        }

        #endregion

        #region 激活会员

        public ActionResult ActiveUser(UserActiveModel model)
        {
            var operId = (Session[SessionConstants.CURRENTOPERATOR] as _operator).oper_id;
            //var operId = 2;
            var user = _userManager.ActiveUser(model, operId);
            if (ModelState.IsValid)
            {
                return Json(new AjaxResultObject
                {
                    code = AjaxResultObject.OK,
                    message = "OK",
                    data = ToUserViewModel(user)
                });
            }
            else
            {
                return Json(new AjaxResultObject
                {
                    code = AjaxResultObject.ERROR,
                    message = "数据校验错误"
                });
            }
        }

        #endregion

        #region 会员分红相关

        // 财务管理 > 会员分红记录
        public ActionResult BonusRecords(int? acc_type,string user_name, string user_phone, DateTime? begin, DateTime? end, int page = 1, int rows = 10)
        {
            if (Request.IsAjaxRequest())
            {
                var pageData = this._userManager.GetBonusRecords(acc_type,user_name, user_phone, begin, end, page, rows);
                var data = pageData.Select(ToBonusRecordViewModel);
                var total = this._userManager.GetBonusRecordsTotal(acc_type,user_name, user_phone, begin, end);
                return Json(new { total = total, rows = data });
            }
            return View();
        }

        private object ToBonusRecordViewModel(account_record b)
        {
            return new
            {
                user_name = b.user.user_name,
                user_phone = b.user.user_phone,
                acc_type = AccountConstants.ToString(b.acc_type),
                bonus_money = b.cons_value,
                bonus_time = b.acc_record_time.ToString("yyyy-MM-dd HH:mm:ss"),
                bonus_remark = b.acc_remark,
                acc_balance = b.acc_balance
            };
        }

        //private object ToBonusRecordViewModel(bonus_record b)
        //{
        //    return new
        //    {
        //        bonus_record_id = b.bonus_record_id,
        //        user_name = b.user.user_name,
        //        user_phone = b.user.user_phone,
        //        bonus_type = b.bouns_type == 1 ? "众筹1分红" : "众筹2分红",
        //        // todo: 由原来的bouns_money改为了bouns_value, 待测试
        //        bonus_money = b.bouns_value,
        //        bonus_time = b.create_time.ToString("yyyy-MM-dd HH:mm:ss"),
        //        bonus_remark = b.bonus_remark
        //    };
        //}

        private object ToUserViewModel(user a)
        {
            return new
            {
                user_id = a.user_id,
                user_status = a.user_status,
                user_code = a.user_code,
                user_name = a.user_name,
                user_phone = a.user_phone,
                id_number = a.id_number,
                province = a.province,
                city = a.city,
                area = a.area,
                address = a.address,
                reg_money = a.reg_money,
                referrer = a.referrer == null ? "无" : a.referrer.user_name + "(" + a.referrer.user_code + ")",
                register_time = a.register_time.ToString("yyyy-MM-dd HH:mm:ss")
            };
        }

        #endregion

        #region 会员提现相关

        /// <summary>
        /// 审核提现
        /// </summary>
        /// <param name="form"></param>
        /// <returns></returns>
        [Route("/User/AuditCashRequest")]
        public bool BachAuditCashRequest(int[] recordIds, int cash_status)
        {
            for (int i = 0; i < recordIds.Length; i++)
            {
                int cashId = recordIds[i];
                //获取对象
                cash_record cashRecord = this._userManager.GetCashRecord(cashId);
                var operId = (Session[SessionConstants.CURRENTOPERATOR] as _operator).oper_id;

                if (cashRecord == null)
                {
                    continue;
                }
                cashRecord.oper_id1 = operId;

                //判断是通过审核还是不通过审核
                //如果不通过
                if (cash_status == CashStatus.AUDIT_DENY)
                {
                    cashRecord.cash_status = CashStatus.AUDIT_DENY;
                    cashRecord.cash_time2 = DateTime.Now;

                    this._userManager.UpdateCashRecord(cashRecord);
                    continue;
                }

                //如果是通过的
                var userAccount = this._userManager.GetUserAccount(cashRecord.user_id);//查会员账户
                int cash_money = cashRecord.cash_money;
                int shou_xu_fei = cashRecord.cash_type==1?Convert.ToInt32(cash_money * CashRate.SHOU_XU_FEI): Convert.ToInt32(cash_money * CashRate.SIVLVER_SHOU_XU_FEI);
                //int fu_xiao_fei = Convert.ToInt32(cash_money * CashRate.FU_XIAO_FEI);
                //判断是否需要的金额，大于了所剩余额
                if (cashRecord.cash_type == CashType.GOLD_DIAMOND) //金钻账户
                {
                    if (userAccount.account1_balance < (cash_money + shou_xu_fei))
                    {
                        cashRecord.cash_status = CashStatus.AUDIT_DENY;
                        cashRecord.cash_time2 = DateTime.Now;
                        cashRecord.cash_remark1 = "审核不成功，该账户余额不足以支付提现扣除";

                        this._userManager.UpdateCashRecord(cashRecord);

                        continue;
                    }
                }
                if (cashRecord.cash_type == CashType.SILVER_DIAMOND || cashRecord.cash_type == CashType.BLUE_DIAMOND) 
                {
                    if (userAccount.account3_balance < (cash_money + shou_xu_fei))
                    {
                        cashRecord.cash_status = CashStatus.AUDIT_DENY;
                        cashRecord.cash_time2 = DateTime.Now;
                        cashRecord.cash_remark1 = "审核不成功，该账户余额不足以支付提现扣除";

                        this._userManager.UpdateCashRecord(cashRecord);

                        continue;
                    }
                }

                cash_record mm = this._userManager.AuidCashRecord(cashRecord);
                if (mm.cash_status == CashStatus.GIVEMONEY_WAITING)
                {
                    var c = mm;
                    continue;
                }
                else
                {
                    continue;
                }
            }
            return true;

        }

        /// <summary>
        /// 单个，要弹出对话框的 审核提现
        /// </summary>
        /// <param name="form"></param>
        /// <returns></returns>
        [Route("/User/AuditCashRequest")]
        public ActionResult AuditCashRequest(FormCollection form)
        {
            var cashRecordId = form["cash_record_id"];

zc/Views/User/AccountBlueDiamond.cshtml
@using zc.Commons;
@{
    ViewBag.Title = "银钻查看";
}

@section style {

}

<header class="mui-bar mui-bar-nav">
    <!-- 防止history.back()回退到上一次查询金钻的页面 -->
    <a onclick="location.href = '@Url.Action("Center", "User")';" class="mui-action-back mui-icon mui-icon-left-nav mui-pull-left"></a>
    <h1 class="mui-title">会员账户 - 银钻</h1>
    <a class="mui-btn mui-btn-red mui-pull-right" onclick="clickSendQuest();">提现</a>
</header>
<div class="mui-content">
    <div id="pullRefreshContainer" class="mui-scroll-wrapper">
        <div class="mui-scroll">
            <h5 class="section-title">账户信息</h5>
            <table class="table table-bordered table-condensed">
                <thead>
                    <tr>
                        <th>累计转入</th>
                        <th>累计转出</th>
                        <th>银钻余额</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>@ViewBag.TotalIncome</td>
                        <td>@ViewBag.TotalExpend</td>
                        <td>@ViewBag.Balance</td>
                    </tr>
                </tbody>
            </table>
            <h5 class="section-title">查询条件</h5>
            <form class="mui-input-group" id="searchForm">
                <div class="mui-input-row">
                    <label>起始日期</label>
                    <input name="dateBegin" value="@Request["dateBegin"]" type="text" class="mui-input-clear datepicker" placeholder="起始日期">
                </div>
                <div class="mui-input-row">
                    <label>终止日期</label>
                    <input name="dateEnd" value="@Request["dateEnd"]" type="text" class="mui-input-clear datepicker" placeholder="终止日期">
                </div>
                <div class="mui-input-row">
                    <label>选择类型</label>
                    <select id="acc_record_type" name="acc_record_type" value="@Request["acc_record_type"]" class="mui-input-clear" style="font-size:14px">
                        <option value="">全部</option>
                        <option value="1">分红(奖金)</option>
                        <option value="2">系统增加</option>
                        <option value="3">提现</option>
                        <option value="4">系统扣减</option>
                        <option value="5">手续费</option>
                    </select>
                </div>
                <button type="submit" class="btn btn-block btn-success">查询</button>
            </form>
            <h5 class="section-title">查询结果</h5>
            <table class="table table-bordered table-condensed">
                <thead>
                    <tr>
                        <th>类型</th>
                        <th>银钻数</th>
                        <th>日期</th>
                    </tr>
                </thead>
                <tbody id="recordList">
                    @*@foreach (var record in ViewBag.RecordList)
            {
                        <tr>
                            <td>@AccRecordType.ToString(record.acc_record_type)</td>
                            @if (record.cons_type == -1)
                {
                                <td style="color:red;">@record.cons_value</td>
                            }
                            else
                            {
                                <td>@record.cons_value</td>
                            }

                            <td>@record.acc_record_time.ToString("yyyy/MM/dd")</td>
                        </tr>
                    }*@
                </tbody>
            </table>
        </div>
    </div>
</div>
@section bottomScript{

    <script type="text/javascript">
        var datePicker = new mui.DtPicker({
            type: 'date'
        });
        $('.datepicker').click(function () {
            var $this = this;
            datePicker.show(function (rs) {
                $this.value = rs.text;
            });
        });

        $('#acc_record_type > option').each(function (i, e) {
            if (e.value == $('#acc_record_type').attr('value')) {
                e.selected = "selected";
            }
        });

        ///点击提现的时候
        function clickSendQuest() {
            if ('@ViewBag.User.wallet_adder' == null || '@ViewBag.User.wallet_adder' == "") {
                //alert("您还不存在钱包地址信息，请先完善资料");
                mui.prompt('', '请输入钱包地址', '', ['确定', '取消'], function (e) {
                    $.ajax({
                        url: "/User/FillUpWalletAddress", // 补填钱包地址
                        type: "POST",
                        data: { wallet_address: e.value },
                        success: function (data) {
                            //如果成功，跳转页面
                            if (data) {
                                location.href = '@Url.Action("CashBlueDiamond", "User")';
                            } else {
                                //失败提示
                                alert("钱包地址提交失败");
                            }
                        }
                    });
                }, 'div');
                return;
            }
            location.href = '@Url.Action("CashBlueDiamond", "User")';
        }

        //上拉加载
        var no_more_data = false;
        var page = 1;
        var rows = 20;
        mui.init({
            pullRefresh: {
                container: "#pullRefreshContainer",//下拉刷新容器标识，querySelector能定位的css选择器均可，比如：id、.class等
                up: {
                    height: 50,//可选,默认50.触发下拉刷新拖动距离,
                    auto: true,//可选,默认false.首次加载自动下拉刷新一次
                    contentdown: "下拉可以刷新",//可选，在下拉可刷新状态时，下拉刷新控件上显示的标题内容
                    contentover: "释放立即刷新",//可选，在释放可刷新状态时，下拉刷新控件上显示的标题内容
                    contentrefresh: "正在加载...",//可选，正在刷新状态时，下拉刷新控件上显示的标题内容
                    contentnomore: "没有更多数据了",
                    callback: pullRefreshHandler //必选，刷新函数，根据具体业务来编写，比如通过ajax从服务器获取新数据；
                }
            }
        });

        function pullRefreshHandler() {
            setTimeout(function () {
                $.ajax({
                    url: "@Url.Action("AccountBlueDiamond", "User")",
                    type: "GET",
                dataType: "json",
                data: $("#searchForm").serializeObject(),
                success: function (result) {
                    if (result.code == 500) {
                        no_more_data = true;
                    } else {
                        $.each(result.data, function (i, val) {
                            $("<tr>").append($("<td>").text(val.acc_record_type))
                            .append($("<td>").text(val.cons_value))
                            .append($("<td>").text(val.acc_record_time))
                            .appendTo($("#recordList"));
                        });
                    }
                    page++;
                    mui('#pullRefreshContainer').pullRefresh().endPullupToRefresh(no_more_data); //refresh completed
                }
            });
        }, 1500);
        }

        // 将form data序列化为json object
        $.fn.serializeObject = function () {
            var o = {};
            var a = this.serializeArray();
            $.each(a, function () {
                if (o[this.name]) {
                    if (!o[this.name].push) {
                        o[this.name] = [o[this.name]];
                    }
                    o[this.name].push(this.value || '');
                } else {
                    o[this.name] = this.value || '';
                }
            });
            o["page"] = page;
            o["rows"] = rows;
            return o;
        }
    </script>
}

zc/Views/User/AccountGoldDiamond.cshtml
@using zc.Commons;
@{
    ViewBag.Title = "金钻查看";
}

@section style {

}

<header class="mui-bar mui-bar-nav">
    <!-- 防止history.back()回退到上一次查询金钻的页面 -->
    <a onclick="location.href = '@Url.Action("Center", "User")';" class="mui-action-back mui-icon mui-icon-left-nav mui-pull-left"></a>
    <h1 class="mui-title">会员账户 - 金钻</h1>
    <a class="mui-btn mui-btn-red mui-pull-right" onclick="clickSendQuest();">提现</a>
</header>
<div class="mui-content">
    <div id="pullRefreshContainer" class="mui-scroll-wrapper">
        <div class="mui-scroll">
            <h5 class="section-title">账户信息</h5>
            <table class="table table-bordered table-condensed">
                <thead>
                    <tr>
                        <th>累计转入</th>
                        <th>累计转出</th>
                        <th>金钻余额</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>@ViewBag.TotalIncome</td>
                        <td>@ViewBag.TotalExpend</td>
                        <td>@ViewBag.Balance</td>
                    </tr>
                </tbody>
            </table>

            <h5 class="section-title">查询条件</h5>
            <form class="mui-input-group" id="searchForm">
                <div class="mui-input-row">
                    <label>起始日期</label>
                    <input name="dateBegin" value="@Request["dateBegin"]" type="text" class="mui-input-clear datepicker" placeholder="起始日期">
                </div>
                <div class="mui-input-row">
                    <label>终止日期</label>
                    <input name="dateEnd" value="@Request["dateEnd"]" type="text" class="mui-input-clear datepicker" placeholder="终止日期">
                </div>
                <div class="mui-input-row">
                    <label>选择类型</label>
                    <select id="acc_record_type" name="acc_record_type" value="@Request["acc_record_type"]" class="mui-input-clear" style="font-size:14px">
                        <option value="">全部</option>
                        <option value="1">分红(奖金)</option>
                        <option value="2">系统增加</option>
                        <option value="3">提现</option>
                        <option value="4">系统扣减</option>
                        <option value="5">手续费</option>
                        <option value="6">充值</option>
                    </select>
                </div>
                <button type="submit" class="btn btn-block btn-success">查询</button>
            </form>
            <h5 class="section-title">查询结果</h5>


            <table class="table table-bordered table-condensed">
                <thead>
                    <tr>
                        <th>类型</th>
                        <th>金钻数</th>
                        <th>日期</th>
                    </tr>
                </thead>
                <tbody id="recordList">
                    @*@foreach (var record in ViewBag.RecordList)
                        {
                            <tr>
                                <td>@AccRecordType.ToString(record.acc_record_type)</td>
                                @if (record.cons_type == -1)
                                {
                                    <td style="color:red;">@record.cons_value</td>
                                }
                                else
                                {
                                    <td>@record.cons_value</td>
                                }

                                <td>@record.acc_record_time.ToString("yyyy/MM/dd")</td>
                            </tr>
                        }*@
                </tbody>
            </table>
        </div>
    </div>
</div>

@section bottomScript{

    <script type="text/javascript">
        var datePicker = new mui.DtPicker({
            type: 'date'
        });
        $('.datepicker').click(function () {
            var $this = this;
            datePicker.show(function (rs) {
                $this.value = rs.text;
            });
        });

        $('#acc_record_type > option').each(function (i, e) {
            if (e.value == $('#acc_record_type').attr('value')) {
                e.selected = "selected";
            }
        });

        ///点击提现的时候
        function clickSendQuest() {
            if ('@ViewBag.User.account_num' == null || '@ViewBag.User.account_num' == "") {
                alert("您还不存在银行卡信息，请先完善资料");
                return;
            }
            location.href = '@Url.Action("CashGoldDiamond", "User")';
        }

        //上拉加载
        var no_more_data = false;
        var page = 1;
        var rows = 20;
        mui.init({
            pullRefresh: {
                container: "#pullRefreshContainer",//下拉刷新容器标识，querySelector能定位的css选择器均可，比如：id、.class等
                up: {
                    height: 50,//可选,默认50.触发下拉刷新拖动距离,
                    auto: true,//可选,默认false.首次加载自动下拉刷新一次
                    contentdown: "下拉可以刷新",//可选，在下拉可刷新状态时，下拉刷新控件上显示的标题内容
                    contentover: "释放立即刷新",//可选，在释放可刷新状态时，下拉刷新控件上显示的标题内容
                    contentrefresh: "正在加载...",//可选，正在刷新状态时，下拉刷新控件上显示的标题内容
                    contentnomore: "没有更多数据了",
                    callback: pullRefreshHandler //必选，刷新函数，根据具体业务来编写，比如通过ajax从服务器获取新数据；
                }
            }
        });

        function pullRefreshHandler() {
            setTimeout(function () {
                $.ajax({
                    url: "@Url.Action("AccountGoldDiamond", "User")",
                    type: "GET",
                    dataType: "json",
                    data: $("#searchForm").serializeObject(),
                    success: function (result) {
                        if (result.code == 500) {
                            no_more_data = true;
                        } else {
                            $.each(result.data, function (i, val) {
                                $("<tr>").append($("<td>").text(val.acc_record_type))
                                .append($("<td>").text(val.cons_value))
                                .append($("<td>").text(val.acc_record_time))
                                .appendTo($("#recordList"));
                            });
                        }
                        page++;
                        mui('#pullRefreshContainer').pullRefresh().endPullupToRefresh(no_more_data); //refresh completed
                    }
                });
            }, 1500);
        }

        // 将form data序列化为json object
        $.fn.serializeObject = function () {
            var o = {};
            var a = this.serializeArray();
            $.each(a, function () {
                if (o[this.name]) {
                    if (!o[this.name].push) {
                        o[this.name] = [o[this.name]];
                    }
                    o[this.name].push(this.value || '');
                } else {
                    o[this.name] = this.value || '';
                }
            });
            o["page"] = page;
            o["rows"] = rows;
            return o;
        }
    </script>
}

zc/Views/User/ChangePwd.cshtml
@{
    ViewBag.Title = "修改密码";
}
<header class="mui-bar mui-bar-nav">
    <a class="mui-action-back mui-icon mui-icon-left-nav mui-pull-left"></a>
    <h1 class="mui-title">@ViewBag.Title</h1>
    <a class="mui-btn mui-btn-red mui-pull-right" href="/User/Center">首页</a>
</header>
<div class="mui-content">
    <form id="loginPwdForm" class="mui-input-group" method="post" action="/User/SaveLoginPwd">
        <h5 class="section-title">登录密码</h5>
        <div class="mui-input-row">
            <label>登录密码</label>
            <input type="password" id="loginPwd" name="loginPwd" placeholder="登录密码" class="mui-input-password mui-input-clear" />
        </div>
        <div class="mui-content-padded">
            <button type="button" onclick="saveLoginPwd()" class="mui-btn mui-btn-primary btn-block">保存</button>
        </div>
    </form>
    <form id="secondPwdForm" class="mui-input-group" method="post" action="/User/SaveSecondPwd">
        <h5 class="section-title">二级密码</h5>
        <div class="mui-input-row">
            <label>二级密码</label>
            <input type="password" id="secondPwd" name="secondPwd" placeholder="二级密码" class="mui-input-password mui-input-clear" />
        </div>
        <div class="mui-content-padded">
            <button type="button" onclick="saveSecondPwd()" class="mui-btn mui-btn-primary btn-block">保存</button>
        </div>
    </form>
</div>

@section bottomScript{
    <script>
        function saveLoginPwd() {
            mui.ajax('@Url.Action("saveLoginPwd", "User")', {
                data: { "loginPwd": $("#loginPwd").val() },
                dataType: 'json',//服务器返回json格式数据
                type: 'post',//HTTP请求类型
                success: function (result) {
                    mui.alert(result.message, "提示");
                }
            });
        }
        function saveSecondPwd() {
            mui.ajax('@Url.Action("saveSecondPwd", "User")', {
                data: { "secondPwd": $("#secondPwd").val() },
                dataType: 'json',//服务器返回json格式数据
                type: 'post',//HTTP请求类型
                success: function (result) {
                    mui.alert(result.message, "提示");
                }
            });
        }
    </script>
}

zc/Views/User/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Global.Index</h2>